# k8s/backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learner-backend
  template:
    metadata:
      labels:
        app: learner-backend
    spec:
      containers:
      - name: backend
        image: jigarmalam/mern-be:latest
        ports:
        - containerPort: 3001
        env:
        - name: MONGO_URI
          value: "mongodb://learner-mongo:27017/your-db"
        # add readiness/liveness probes if you want
---
apiVersion: v1
kind: Service
metadata:
  name: learner-backend
spec:
  type: NodePort
  ports:
  - port: 3001
    targetPort: 3001
    nodePort: 30081
  selector:
    app: learner-backend