apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: learner-frontend
  template:
    metadata:
      labels:
        app: learner-frontend
    spec:
      containers:
      - name: frontend
        image: jigarmalam/mern-fe:latest
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_API_BASE_URL
          value: "http://learner-backend:3001"
---
apiVersion: v1
kind: Service
metadata:
  name: learner-frontend
spec:
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: learner-frontend
---
# optional Ingress (requires ingress controller)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: learner-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: learner-frontend
            port:
              number: 80