apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: learner-mongo
  template:
    metadata:
      labels:
        app: learner-mongo
    spec:
      containers:
      - name: mongo
        image: mongo:6
        ports:
        - containerPort: 27017
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: learner-mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: learner-mongo
