apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mern-chart.fullname" . }}-frontend
  labels:
    app: {{ include "mern-chart.name" . }}-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "mern-chart.name" . }}-frontend
  template:
    metadata:
      labels:
        app: {{ include "mern-chart.name" . }}-frontend
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          imagePullPolicy: {{ .Values.frontend.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
